show_detail= true # 显示主机详情
[options] # 全局配置
server_alive_interval= 30 # 发送心跳包时间，同 ssh -o ServerAliveInterval=30

[[servers]]
name= "vagrant" # 显示名称
ip="192.168.33.10" # 主机地址
port= 22 # 端口号，可省略，默认为22
user= "root" # 用户名
password="vagrant" # 密码，使用无密码的key登录时可省略
method="password" # 认证方式，可省略，默认值为password，可选项有password、key
key="" # 密钥路径，method=key时有效，可省略，默认为~/.ssh/id_rsa
[servers.options] # 自定义配置，会覆盖配置中相同的值
server_alive_interval= 20


[[servers]]
name="vagrant-key"
ip="192.168.33.10"
user="root"
method="key"

[[groups]]
group_name="your group name"
prefix="a"
[[groups.servers]]
name="example1"
ip="192.168.33.10"
user="root"
password="root"
[[groups.servers]]
name="example2"
ip="192.168.33.10"
user="root"
password="root"

[[groups]]
group_name="group2"
prefix="b"
[[groups.servers]]
name=""
